import { useEffect, useMemo, useState, type CSSProperties } from 'react';
import { AlertTriangle, Bus, CalendarDays, Camera, Check, ChevronDown, CircleDollarSign, Clock3, CloudRain, CloudSun, Copy, Droplets, ExternalLink, Loader2, MapPin, Minus, Navigation, NotebookPen, PencilLine, Plus, RefreshCw, Sparkles, Sun, Sunrise, Sunset, ThermometerSun, TrainFront, Umbrella, Utensils, Wind } from 'lucide-react';
import type { TravelPlan } from '../utils/aiGenerator';
import type { RoutePoint, SmartRoute } from '../types/route';
import { budgetTotal, calculateTimeline, type BudgetItem, type PlannedRoutePoint, type TripRequest } from '../domain/trip';
import { useTrip } from '../state/tripStore';
import { RouteMap } from './RouteMap';

type Tab = 'overview' | 'stops' | 'days' | 'weather' | 'transport' | 'food' | 'budget';
const tabs: Array<{ id: Tab; label: string; icon: typeof MapPin }> = [
  { id: 'overview', label: '概览', icon: Sparkles }, { id: 'stops', label: '路线', icon: MapPin },
  { id: 'days', label: '行程记录', icon: CalendarDays }, { id: 'weather', label: '天气', icon: CloudSun },
  { id: 'transport', label: '交通', icon: Bus }, { id: 'food', label: '美食', icon: Utensils },
  { id: 'budget', label: '预算', icon: CircleDollarSign },
];

export function MapWorkspace({ route, plan, selectedPointId, activePointIndex, navigating, imageUrl, onSelectPoint, onRegenerate, onCopySocial, onSimulateNavigation }: {
  route: SmartRoute; plan: TravelPlan; selectedPointId?: string; activePointIndex: number; navigating: boolean; imageUrl: string;
  onSelectPoint: (point: RoutePoint) => void; onRegenerate?: () => void; onCopySocial?: () => void; onSimulateNavigation?: () => void;
}) {
  const { plan: tripPlan, request, isReplanning, patchPlan, updatePlanSettings, updateBudgetItems, setBudgetTotal, updateRequest } = useTrip();
  const [tab, setTab] = useState<Tab>('overview');
  const [mobilePane, setMobilePane] = useState<'map' | 'details'>('map');
  const selected = route.points.find((point) => point.id === selectedPointId) as PlannedRoutePoint | undefined ?? route.points[0] as PlannedRoutePoint;
  const patchRoutePoint = (id: string, changes: Partial<PlannedRoutePoint>) => patchPlan((value) => {
    const source: PlannedRoutePoint[] = (value.route.points as PlannedRoutePoint[]).map((point) => point.id === id ? { ...point, ...changes } as PlannedRoutePoint : point);
    const points = changes.durationMinutes === undefined
      ? source
      : calculateTimeline(source, value.settings.departureTime);
    return {
      ...value,
      route: { ...value.route, points },
      settings: {
        ...value.settings,
        targetDurationMinutes: points.reduce((sum, point) => sum + point.durationMinutes + point.travelMinutesToNext, 0),
      },
    };
  });
  if (!tripPlan) return null;

  return <section className="overflow-hidden rounded-[2rem] border border-ink/10 bg-white shadow-soft">
    <div className="border-b border-ink/10 bg-ink p-2 lg:hidden" role="tablist" aria-label="移动端工作区">
      <div className="grid grid-cols-2 rounded-full bg-white/10 p-1">{(['map', 'details'] as const).map((pane) => <button key={pane} type="button" role="tab" aria-selected={mobilePane === pane} onClick={() => setMobilePane(pane)} className={`rounded-full px-4 py-2 text-sm font-black ${mobilePane === pane ? 'bg-white text-ink' : 'text-white'}`}>{pane === 'map' ? '地图' : '详情'}</button>)}</div>
    </div>
    <div className="grid lg:h-[760px] lg:grid-cols-[72px_minmax(0,1fr)_420px]">
      <nav className={`${mobilePane === 'details' ? 'flex' : 'hidden'} gap-2 overflow-x-auto bg-ink p-2 text-white lg:flex lg:flex-col lg:justify-center`} aria-label="方案详情标签">
        {tabs.map(({ id, label, icon: Icon }) => <button key={id} type="button" aria-pressed={tab === id} aria-label={label} onClick={() => { setTab(id); setMobilePane('details'); }} className={`flex shrink-0 items-center gap-2 rounded-2xl px-3 py-2 text-xs font-black lg:flex-col lg:px-2 ${tab === id ? 'bg-river text-white' : 'text-white/65 hover:bg-white/10'}`}><Icon className="h-5 w-5" /><span>{label}</span></button>)}
      </nav>

      <div role="region" aria-label="路线地图" className={`${mobilePane === 'map' ? 'block' : 'hidden'} relative min-h-[620px] min-w-0 overflow-hidden border-ink/10 lg:block lg:border-r`}>
        <div className="absolute left-4 top-4 z-20 flex flex-wrap gap-2">
          <CommandButton icon={isReplanning ? Loader2 : RefreshCw} label={isReplanning ? '计算中' : '重新规划'} disabled={isReplanning} onClick={onRegenerate} spin={isReplanning} />
          <CommandButton icon={Copy} label="复制文案" onClick={onCopySocial} />
        </div>
        <RouteMap route={route} selectedPointId={selectedPointId} activePointIndex={activePointIndex} navigating={navigating} onSelectPoint={onSelectPoint} mapOnly />
        <div className="pointer-events-none absolute bottom-4 left-4 right-4 z-20 grid gap-2 sm:grid-cols-3"><Metric label="规则估算距离" value={`${route.totalDistanceKm.toFixed(1)} km`} /><Metric label="出发时间" value={tripPlan.settings.departureTime} /><Metric label="当前点到达" value={selected?.arrivalTime ?? selected?.time ?? '--:--'} /></div>
      </div>

      <aside aria-label="方案详情" className={`${mobilePane === 'details' ? 'flex' : 'hidden'} min-h-0 min-w-0 flex-col overflow-hidden bg-[#fffdf7] lg:flex`}>
        <div className="min-h-0 flex-1 overflow-y-auto overscroll-contain p-5 [scrollbar-gutter:stable]">
          {tab === 'overview' && <Overview plan={tripPlan} route={route} summary={plan.summary} onSettings={updatePlanSettings} onBudget={setBudgetTotal} onDate={(startDate) => updateRequest({ startDate })} />}
          {tab === 'stops' && <Stops points={route.points as PlannedRoutePoint[]} selectedId={selectedPointId} fallbackImageUrl={imageUrl} dailyRecords={tripPlan.dailyRecords} maxDays={request.days} onSelect={onSelectPoint} onPatchPoint={patchRoutePoint} onPatchNote={(id, note) => patchPlan((value) => ({ ...value, pointNotes: { ...value.pointNotes, [id]: note } }))} notes={tripPlan.pointNotes} />}
          {tab === 'days' && <Days plan={tripPlan} onPatch={patchPlan} />}
          {tab === 'weather' && <Weather request={request} lat={route.points[0]?.lat} lng={route.points[0]?.lng} />}
          {tab === 'transport' && <Transport onSimulate={onSimulateNavigation} />}
          {tab === 'food' && <Food plan={tripPlan} />}
          {tab === 'budget' && <Budget items={tripPlan.budgetItems} target={request.budget} onChange={updateBudgetItems} />}
        </div>
      </aside>
    </div>
  </section>;
}

function Overview({ plan, route, summary, onSettings, onBudget, onDate }: { plan: NonNullable<ReturnType<typeof useTrip>['plan']>; route: SmartRoute; summary: string; onSettings: ReturnType<typeof useTrip>['updatePlanSettings']; onBudget: (total: number) => void; onDate: (date: string) => void }) {
  return <div className="space-y-4"><section className="rounded-[1.65rem] bg-ink p-5 text-white"><div className="text-[10px] font-black uppercase tracking-[0.2em] text-jade">已保存方案 · 自动同步</div><h3 className="mt-2 font-display text-2xl font-black leading-tight">{route.title}</h3><p className="mt-3 text-sm leading-6 text-white/65">{summary}</p></section><h4 className="font-display text-2xl font-black">路线总览</h4><div className="grid grid-cols-2 gap-3"><EditableMetric label="点位" value={plan.settings.targetPointCount} min={2} max={plan.route.points.length} suffix="个" onCommit={(value) => onSettings({ targetPointCount: value })} /><EditableMetric label="预计时长" value={Math.round(plan.settings.targetDurationMinutes / 6) / 10} min={1} max={24} step={0.5} suffix="小时" onCommit={(value) => onSettings({ targetDurationMinutes: Math.round(value * 60) })} /><EditableMetric label="预算总计" value={budgetTotal(plan.budgetItems)} min={0} max={999999} prefix="¥" onCommit={onBudget} /><label className="rounded-2xl bg-white p-4 shadow-sm"><span className="block text-xs font-black text-ink/50">出发日期</span><input aria-label="总览出发日期" type="date" value={plan.requestSnapshot.startDate} onChange={(event) => onDate(event.target.value)} className="focus-ring mt-2 w-full bg-transparent font-display text-lg font-black text-ink" /></label></div><div className="rounded-3xl bg-white p-4 shadow-sm"><label className="block text-xs font-black text-ink/60">出发时间<input type="time" value={plan.settings.departureTime} onChange={(event) => onSettings({ departureTime: event.target.value })} className="focus-ring mt-2 w-full rounded-xl border border-ink/10 px-3 py-2 text-sm" /></label></div><p className="rounded-2xl bg-jade/10 p-3 text-xs font-bold leading-5 text-ink/60">修改上方数字或日期后会自动保存，并同步更新预算、每日日期和时间线。</p></div>;
}

function Stops({ points, selectedId, fallbackImageUrl, dailyRecords, maxDays, onSelect, onPatchPoint, notes, onPatchNote }: { points: PlannedRoutePoint[]; selectedId?: string; fallbackImageUrl: string; dailyRecords: Array<{ day: number; date: string }>; maxDays: number; onSelect: (point: RoutePoint) => void; onPatchPoint: (id: string, changes: Partial<PlannedRoutePoint>) => void; notes: Record<string, string>; onPatchNote: (id: string, note: string) => void }) {
  const [expandedId, setExpandedId] = useState<string | null>(selectedId ?? points[0]?.id ?? null);
  return <div className="space-y-4"><div><h4 className="font-display text-2xl font-black">地点安排</h4><p className="mt-1 text-xs font-bold leading-5 text-ink/50">展开地点卡片查看实景、游览重点与个人安排；修改内容会自动保存。</p></div>{points.map((point, index) => { const expanded = expandedId === point.id; const date = dailyRecords.find((record) => record.day === (point.day ?? 1))?.date; const detailUrl = `https://uri.amap.com/search?keyword=${encodeURIComponent(`${point.city} ${point.name}`)}&city=${encodeURIComponent(point.city)}`; return <article key={point.id} className={`overflow-hidden rounded-[1.65rem] border bg-white transition ${selectedId === point.id ? 'border-river shadow-[0_12px_35px_rgba(14,116,128,.14)]' : 'border-ink/10 shadow-sm'}`}>
      <button type="button" aria-expanded={expanded} onClick={() => { setExpandedId(expanded ? null : point.id); onSelect(point); }} className="group relative block h-36 w-full overflow-hidden text-left">
        <img src={point.imageUrl ?? fallbackImageUrl} alt={`${point.name}地点照片`} className="h-full w-full object-cover transition duration-500 group-hover:scale-[1.035]" />
        <span className="absolute inset-0 bg-gradient-to-t from-ink/95 via-ink/20 to-transparent" />
        <span className="absolute left-4 top-4 rounded-full bg-white/90 px-2.5 py-1 text-[10px] font-black text-ink backdrop-blur">{String(index + 1).padStart(2, '0')} · {point.type === 'start' ? '出发点' : '路线点'}</span>
        <span className="absolute bottom-4 left-4 right-4 flex items-end justify-between gap-3 text-white"><span><strong className="block font-display text-xl font-black">{point.name}</strong><span className="mt-1 flex items-center gap-2 text-[11px] font-bold text-white/70"><CalendarDays className="h-3.5 w-3.5" />{formatCompactDate(date)}<Clock3 className="ml-1 h-3.5 w-3.5" />{point.arrivalTime}</span></span><ChevronDown className={`h-5 w-5 shrink-0 transition ${expanded ? 'rotate-180' : ''}`} /></span>
      </button>
      {!expanded && <div className="flex items-center justify-between gap-3 px-4 py-3 text-xs font-bold text-ink/55"><span className="line-clamp-1">{point.reason}</span><span className="shrink-0 text-river">展开安排</span></div>}
      {expanded && <div className="space-y-4 p-4">
        <p className="text-sm font-bold leading-6 text-ink/65">{point.reason}</p>
        <div className="grid grid-cols-2 gap-2 text-xs font-bold"><InfoTile icon={Clock3} label="停留时间" value={`${point.durationMinutes} 分钟`} /><InfoTile icon={Navigation} label="下一段交通" value={point.travelMinutesToNext ? `${point.travelMinutesToNext} 分钟` : '行程终点'} /></div>
        <div className="space-y-2 rounded-2xl bg-[#f1f6f2] p-3 text-xs leading-5 text-ink/65"><p className="flex gap-2"><Camera className="mt-0.5 h-4 w-4 shrink-0 text-river" /><span><strong className="text-ink">拍摄建议：</strong>{point.photoTip}</span></p><p className="flex gap-2"><NotebookPen className="mt-0.5 h-4 w-4 shrink-0 text-tower" /><span><strong className="text-ink">记录重点：</strong>{point.recordTip}</span></p></div>
        <section className="rounded-2xl border border-ink/10 p-3"><div className="mb-3 flex items-center justify-between"><strong className="text-sm">我的地点安排</strong><span className="rounded-full bg-jade/10 px-2 py-1 text-[10px] font-black text-jade">自动保存</span></div><div className="grid grid-cols-2 gap-2"><label className="text-[11px] font-black text-ink/50">安排日期<select value={point.day ?? 1} onChange={(event) => onPatchPoint(point.id, { day: Number(event.target.value) })} className="focus-ring mt-1 w-full rounded-xl border border-ink/10 bg-white px-2 py-2 text-sm font-bold text-ink">{Array.from({ length: maxDays }, (_, day) => <option key={day + 1} value={day + 1}>第{day + 1}天</option>)}</select></label><label className="text-[11px] font-black text-ink/50">停留分钟<input type="number" min={10} max={480} step={5} value={point.durationMinutes} onChange={(event) => onPatchPoint(point.id, { durationMinutes: Math.max(10, Number(event.target.value) || 10) })} className="focus-ring mt-1 w-full rounded-xl border border-ink/10 px-2 py-2 text-sm font-bold text-ink" /></label></div><label className="mt-3 block text-[11px] font-black text-ink/50">我的安排<textarea value={notes[point.id] ?? ''} placeholder="例如：提前预约、重点拍摄坝体全景、为老人预留休息时间" onChange={(event) => onPatchNote(point.id, event.target.value)} rows={3} className="focus-ring mt-1 w-full resize-none rounded-xl border border-ink/10 px-3 py-2 text-sm font-medium text-ink" /></label></section>
        <div className="flex items-center justify-between gap-3">{point.imageCredit ? <a href={point.imageCredit.sourceUrl} target="_blank" rel="noreferrer" className="text-[10px] font-bold text-ink/40 underline decoration-ink/20 underline-offset-2">{point.imageCredit.author} · {point.imageCredit.license}</a> : <span className="text-[10px] font-bold text-ink/40">城市授权代表图</span>}<a href={detailUrl} target="_blank" rel="noreferrer" className="inline-flex shrink-0 items-center gap-1 rounded-full bg-ink px-3 py-2 text-xs font-black text-white">查看地点详情<ExternalLink className="h-3.5 w-3.5" /></a></div>
      </div>}
    </article>; })}</div>;
}

function InfoTile({ icon: Icon, label, value }: { icon: typeof Clock3; label: string; value: string }) { return <div className="rounded-2xl bg-ink/[0.045] p-3"><Icon className="mb-2 h-4 w-4 text-river" /><span className="block text-[10px] text-ink/45">{label}</span><strong className="mt-0.5 block text-ink">{value}</strong></div>; }
function formatCompactDate(value?: string) { if (!value) return '日期待定'; const date = new Date(`${value}T00:00:00`); return new Intl.DateTimeFormat('zh-CN', { month: 'numeric', day: 'numeric', weekday: 'short' }).format(date); }

function Days({ plan, onPatch }: { plan: NonNullable<ReturnType<typeof useTrip>['plan']>; onPatch: ReturnType<typeof useTrip>['patchPlan'] }) {
  const [editingId, setEditingId] = useState<string | null>(null);
  const [celebratingId, setCelebratingId] = useState<string | null>(null);
  const updatePoint = (pointId: string, changes: Partial<PlannedRoutePoint>) => onPatch((value) => ({ ...value, route: { ...value.route, points: (value.route.points as PlannedRoutePoint[]).map((point) => point.id === pointId ? { ...point, ...changes } : point) } }));
  const updateTime = (pointId: string, nextTime: string) => onPatch((value) => {
    const points = value.route.points as PlannedRoutePoint[];
    const index = points.findIndex((point) => point.id === pointId);
    if (index < 0) return value;
    const target = points[index];
    const delta = clockMinutes(nextTime) - clockMinutes(target.arrivalTime);
    return { ...value, route: { ...value.route, points: points.map((point, pointIndex) => pointIndex >= index && point.day === target.day ? { ...point, arrivalTime: shiftClock(point.arrivalTime, delta), time: shiftClock(point.arrivalTime, delta) } : point) } };
  });
  const togglePoint = (day: number, pointId: string, checked: boolean) => {
    onPatch((value) => ({ ...value, dailyRecords: value.dailyRecords.map((item) => item.day === day ? { ...item, checkedPointIds: checked ? item.checkedPointIds.filter((id) => id !== pointId) : [...item.checkedPointIds, pointId] } : item) }));
    if (!checked) { setCelebratingId(pointId); window.setTimeout(() => setCelebratingId((current) => current === pointId ? null : current), 900); }
  };
  return <div className="space-y-5"><div className="flex items-end justify-between"><div><h4 className="font-display text-2xl font-black">每日记录</h4><p className="mt-1 text-xs font-bold text-ink/45">点击任务完成打卡，铅笔可修改时间与任务名称。</p></div><span className="rounded-full bg-jade/10 px-3 py-1 text-[10px] font-black text-jade">自动保存</span></div>{plan.dailyRecords.map((record) => { const points = plan.route.points.filter((point) => (point.day ?? 1) === record.day) as PlannedRoutePoint[]; const date = new Date(`${record.date}T00:00:00`); const dateTitle = new Intl.DateTimeFormat('zh-CN', { month: 'long', day: 'numeric', weekday: 'long' }).format(date); const completed = points.filter((point) => record.checkedPointIds.includes(point.id)).length; return <section key={record.day} className="itinerary-paper relative overflow-hidden rounded-[1.75rem] border border-ink/10 px-5 pb-5 pt-6 shadow-[0_14px_38px_rgba(18,34,42,.08)]">
    <div className="relative z-10 mb-5 flex items-start justify-between border-b-2 border-ink/10 pb-4 pl-8"><div><span className="text-[10px] font-black uppercase tracking-[0.22em] text-tower">DAY {String(record.day).padStart(2, '0')}</span><h5 className="mt-1 font-display text-2xl font-black leading-none text-ink">{dateTitle}</h5><p className="mt-2 text-[11px] font-bold text-ink/40">{record.date}</p></div><div className="grid h-12 w-12 place-items-center rounded-full border border-river/15 bg-white/80 text-center shadow-sm"><strong className="text-sm text-river">{completed}/{points.length}</strong><span className="-mt-1 text-[8px] font-black text-ink/40">完成</span></div></div>
    <div className="relative z-10 space-y-1 pl-8">{points.map((point) => { const checked = record.checkedPointIds.includes(point.id); const editing = editingId === point.id; return <div key={point.id} className="relative min-h-[52px] py-1">{celebratingId === point.id && <Confetti />}{editing ? <div className="grid grid-cols-[86px_1fr_36px] items-center gap-2 rounded-xl bg-white/90 p-2 shadow-sm"><label className="sr-only" htmlFor={`time-${point.id}`}>修改{point.name}时间</label><input id={`time-${point.id}`} aria-label={`修改${point.name}时间`} type="time" value={point.arrivalTime} onChange={(event) => updateTime(point.id, event.target.value)} className="focus-ring min-w-0 rounded-lg border border-ink/10 px-2 py-2 text-xs font-black text-river" /><label className="sr-only" htmlFor={`name-${point.id}`}>修改任务名称</label><input id={`name-${point.id}`} aria-label={`修改${point.name}任务`} value={point.name} onChange={(event) => updatePoint(point.id, { name: event.target.value })} className="focus-ring min-w-0 rounded-lg border border-ink/10 px-2 py-2 text-sm font-bold" /><button type="button" aria-label={`完成编辑${point.name}`} onClick={() => setEditingId(null)} className="grid h-9 w-9 place-items-center rounded-lg bg-jade text-white"><Check className="h-4 w-4" /></button></div> : <div className="group flex min-h-[46px] items-center gap-2"><button type="button" aria-pressed={checked} aria-label={`${checked ? '取消完成' : '完成'}${point.name}`} onClick={() => togglePoint(record.day, point.id, checked)} className={`flex min-w-0 flex-1 items-center gap-3 rounded-xl px-2 py-2 text-left transition ${checked ? 'text-ink/30' : 'hover:bg-white/60'}`}><span className={`grid h-6 w-6 shrink-0 place-items-center rounded-full border-2 transition ${checked ? 'scale-110 border-jade bg-jade text-white' : 'border-river/30 bg-white text-transparent'}`}><Check className="h-3.5 w-3.5" /></span><span className={`w-12 shrink-0 font-display text-sm font-black ${checked ? 'text-ink/25' : 'text-river'}`}>{point.arrivalTime}</span><span className={`relative min-w-0 flex-1 font-bold transition after:absolute after:left-0 after:top-1/2 after:h-[2px] after:bg-tower after:transition-all ${checked ? 'text-ink/30 after:w-full' : 'after:w-0'}`}>{point.name}</span></button><button type="button" aria-label={`编辑${point.name}`} onClick={() => setEditingId(point.id)} className="grid h-9 w-9 shrink-0 place-items-center rounded-full text-ink/35 transition hover:bg-river/10 hover:text-river"><PencilLine className="h-4 w-4" /></button></div>}</div>; })}</div>
    <label className="relative z-10 mt-4 block pl-8 text-[11px] font-black text-ink/45">今日手记<textarea aria-label={`第${record.day}天手记`} value={record.note} placeholder="写下今天的天气、心情或临时调整……" onChange={(event) => onPatch((value) => ({ ...value, dailyRecords: value.dailyRecords.map((item) => item.day === record.day ? { ...item, note: event.target.value } : item) }))} rows={3} className="focus-ring mt-2 w-full resize-none rounded-2xl border border-ink/10 bg-white/55 px-4 py-3 font-medium leading-7 text-ink placeholder:text-ink/25" /></label>
  </section>; })}</div>;
}

function Confetti() { const colors = ['bg-tower', 'bg-jade', 'bg-river', 'bg-amber-400', 'bg-violet-500', 'bg-rose-400']; return <span aria-hidden="true" className="pointer-events-none absolute inset-x-0 top-1/2 z-20">{colors.map((color, index) => <i key={color} className={`confetti-piece ${color}`} style={{ '--confetti-angle': `${index * 60}deg`, '--confetti-x': `${(index - 2.5) * 18}px` } as CSSProperties} />)}</span>; }
function clockMinutes(value: string) { const [hours, minutes] = value.split(':').map(Number); return (hours || 0) * 60 + (minutes || 0); }
function shiftClock(value: string, delta: number) { const total = ((clockMinutes(value) + delta) % 1440 + 1440) % 1440; return `${String(Math.floor(total / 60)).padStart(2, '0')}:${String(total % 60).padStart(2, '0')}`; }

type WeatherHour = { time: string; temperature: number; rainProbability: number; code: number };
type WeatherDay = { date: string; code: number; max: number; min: number; rainProbability: number; sunrise: string; sunset: string; uv: number };
type WeatherData = { temperature: number; apparentTemperature: number; humidity: number; precipitation: number; code: number; windSpeed: number; windGusts: number; hourly: WeatherHour[]; daily: WeatherDay[]; fetchedAt: string };
function Weather({ request, lat, lng }: { request: TripRequest; lat?: number; lng?: number }) {
  const [weather, setWeather] = useState<WeatherData | null>(null);
  const [dataState, setDataState] = useState<'请求中' | '实时' | '30分钟缓存' | '请求失败'>('请求中');
  const [reason, setReason] = useState('');
  useEffect(() => { let alive = true; const key = `weather-v2-${request.destinationCity}`; const cached = localStorage.getItem(key); if (cached) { try { const value = JSON.parse(cached) as WeatherData; if (value.daily?.length && Date.now() - new Date(value.fetchedAt).getTime() < 1800000) { setWeather(value); setDataState('30分钟缓存'); return; } } catch { /* ignore invalid cache */ } } if (!lat || !lng) { setDataState('请求失败'); setReason('路线缺少经纬度，无法请求天气；请先重新生成路线。'); return; } const url = `https://api.open-meteo.com/v1/forecast?latitude=${lat}&longitude=${lng}&current=temperature_2m,relative_humidity_2m,apparent_temperature,precipitation,weather_code,wind_speed_10m,wind_gusts_10m&hourly=temperature_2m,precipitation_probability,weather_code&daily=weather_code,temperature_2m_max,temperature_2m_min,precipitation_probability_max,sunrise,sunset,uv_index_max&timezone=Asia%2FShanghai&forecast_days=7`; fetch(url).then((response) => { if (!response.ok) throw new Error(`HTTP ${response.status}`); return response.json(); }).then((data) => { const currentIndex = Math.max(0, data.hourly.time.findIndex((time: string) => time >= data.current.time)); const value: WeatherData = { temperature: data.current.temperature_2m, apparentTemperature: data.current.apparent_temperature, humidity: data.current.relative_humidity_2m, precipitation: data.current.precipitation, code: data.current.weather_code, windSpeed: data.current.wind_speed_10m, windGusts: data.current.wind_gusts_10m, hourly: data.hourly.time.slice(currentIndex, currentIndex + 8).map((time: string, index: number) => ({ time, temperature: data.hourly.temperature_2m[currentIndex + index], rainProbability: data.hourly.precipitation_probability[currentIndex + index] ?? 0, code: data.hourly.weather_code[currentIndex + index] })), daily: data.daily.time.map((date: string, index: number) => ({ date, code: data.daily.weather_code[index], max: data.daily.temperature_2m_max[index], min: data.daily.temperature_2m_min[index], rainProbability: data.daily.precipitation_probability_max[index] ?? 0, sunrise: data.daily.sunrise[index], sunset: data.daily.sunset[index], uv: data.daily.uv_index_max[index] ?? 0 })), fetchedAt: new Date().toISOString() }; localStorage.setItem(key, JSON.stringify(value)); if (alive) { setWeather(value); setDataState('实时'); setReason(''); } }).catch((error) => { if (alive) { setWeather(null); setDataState('请求失败'); setReason(`Open‑Meteo 请求失败：${error instanceof Error ? error.message : '未知错误'}。暂不提供推测数据，请出发前改用官方天气服务核验。`); } }); return () => { alive = false; }; }, [request.destinationCity, lat, lng]);
  const today = weather?.daily[0]; const advice = weather ? buildWeatherAdvice(weather, request) : [];
  return <div className="space-y-4"><div><h4 className="font-display text-2xl font-black">出行天气</h4><p className="mt-1 text-xs font-bold leading-5 text-ink/45">把天气数据翻译成今天真正需要的出行准备。</p></div>{weather ? <>
    <section className="relative overflow-hidden rounded-[1.75rem] bg-gradient-to-br from-river via-[#127f8c] to-[#0a5964] p-5 text-white shadow-[0_18px_45px_rgba(14,107,114,.2)]"><Sun className="absolute -right-8 -top-8 h-36 w-36 text-white/10" /><div className="relative flex items-start justify-between"><div><span className="rounded-full bg-white/15 px-3 py-1 text-[10px] font-black backdrop-blur">{request.destinationCity} · {dataState}</span><div className="mt-4 flex items-end gap-3"><strong className="font-display text-6xl font-black leading-none">{Math.round(weather.temperature)}°</strong><div className="pb-1"><p className="text-sm font-black">{weatherLabel(weather.code)}</p><p className="mt-1 text-xs font-bold text-white/65">体感 {Math.round(weather.apparentTemperature)}°</p></div></div></div><div className="rounded-2xl bg-white/10 px-3 py-2 text-right text-xs font-bold backdrop-blur"><p>最高 {Math.round(today?.max ?? weather.temperature)}°</p><p className="mt-1 text-white/60">最低 {Math.round(today?.min ?? weather.temperature)}°</p></div></div><div className="relative mt-5 grid grid-cols-3 gap-2"><WeatherHeroMetric icon={Droplets} label="湿度" value={`${weather.humidity}%`} /><WeatherHeroMetric icon={Umbrella} label="降雨概率" value={`${today?.rainProbability ?? 0}%`} /><WeatherHeroMetric icon={Wind} label="阵风" value={`${Math.round(weather.windGusts)} km/h`} /></div></section>
    <section className="rounded-[1.5rem] border border-tower/15 bg-[#fff8ed] p-4"><div className="flex items-center gap-2"><span className="grid h-9 w-9 place-items-center rounded-full bg-tower text-white"><Sparkles className="h-4 w-4" /></span><div><h5 className="font-black">结合行程的准备建议</h5><p className="text-[10px] font-bold text-ink/40">依据天气阈值与“{request.travelerType}”条件生成</p></div></div><ul className="mt-3 space-y-2">{advice.map((item) => <li key={item} className="flex gap-2 text-xs font-bold leading-5 text-ink/65"><span className="mt-1.5 h-1.5 w-1.5 shrink-0 rounded-full bg-tower" />{item}</li>)}</ul></section>
    <section><div className="mb-2 flex items-end justify-between"><h5 className="font-display text-lg font-black">接下来 8 小时</h5><span className="text-[10px] font-bold text-ink/35">小时预报</span></div><div className="grid grid-cols-4 gap-2">{weather.hourly.map((hour) => <div key={hour.time} className="rounded-2xl border border-ink/8 bg-white p-2.5 text-center shadow-sm"><span className="text-[10px] font-black text-ink/40">{hour.time.slice(11, 16)}</span><CloudSun className="mx-auto my-2 h-5 w-5 text-river" /><strong className="block text-sm">{Math.round(hour.temperature)}°</strong><span className="mt-1 block text-[9px] font-bold text-river">雨 {hour.rainProbability}%</span></div>)}</div></section>
    <section className="rounded-[1.5rem] bg-white p-4 shadow-sm"><h5 className="font-display text-lg font-black">行程期间</h5><div className="mt-3 space-y-3">{weather.daily.slice(0, Math.min(3, Math.max(1, request.days))).map((day, index) => <div key={day.date} className="grid grid-cols-[70px_1fr_auto] items-center gap-3 border-b border-ink/8 pb-3 last:border-0 last:pb-0"><div><strong className="text-xs">{index === 0 ? '今天' : `第${index + 1}天`}</strong><span className="mt-1 block text-[9px] font-bold text-ink/35">{day.date.slice(5).replace('-', '/')}</span></div><div><p className="text-xs font-black">{weatherLabel(day.code)}</p><p className="mt-1 text-[10px] font-bold text-ink/40">降雨 {day.rainProbability}% · UV {day.uv.toFixed(1)}</p></div><strong className="text-sm">{Math.round(day.min)}°–{Math.round(day.max)}°</strong></div>)}</div>{today && <div className="mt-4 grid grid-cols-2 gap-2"><MiniFact icon={Sunrise} label="日出" value={today.sunrise.slice(11, 16)} /><MiniFact icon={Sunset} label="日落" value={today.sunset.slice(11, 16)} /></div>}</section>
  </> : <div className="rounded-[1.5rem] border border-dashed border-tower/35 bg-tower/5 p-5"><CloudRain className="h-7 w-7 text-tower" /><h5 className="mt-3 font-black">暂时无法取得天气数据</h5><p className="mt-2 text-xs font-bold leading-5 text-ink/55">{reason || '正在连接 Open‑Meteo，请稍候。'}</p></div>}<section className="rounded-2xl border border-ink/8 bg-white/70 p-3 text-[10px] font-bold leading-5 text-ink/45"><p>数据源：<a className="font-black text-river underline" href="https://open-meteo.com/" target="_blank" rel="noreferrer">Open‑Meteo Weather Forecast API</a></p><p>状态：{dataState} · 30分钟本机缓存</p><p>更新时间：{weather ? new Intl.DateTimeFormat('zh-CN', { dateStyle: 'long', timeStyle: 'short', timeZone: 'Asia/Shanghai' }).format(new Date(weather.fetchedAt)) : '未取得数据'}</p><p>时区：Asia/Shanghai（UTC+8） · 预报可能变化，关键行程请临行复核。</p></section></div>;
}

function WeatherHeroMetric({ icon: Icon, label, value }: { icon: typeof Droplets; label: string; value: string }) { return <div className="rounded-2xl bg-white/10 p-2.5 backdrop-blur"><Icon className="h-4 w-4 text-white/70" /><span className="mt-2 block text-[9px] font-bold text-white/50">{label}</span><strong className="mt-0.5 block text-xs">{value}</strong></div>; }
function MiniFact({ icon: Icon, label, value }: { icon: typeof Sunrise; label: string; value: string }) { return <div className="flex items-center gap-2 rounded-xl bg-ink/[0.035] p-2.5"><Icon className="h-4 w-4 text-tower" /><span className="text-[10px] font-bold text-ink/40">{label}</span><strong className="ml-auto text-xs">{value}</strong></div>; }
function weatherLabel(code: number) { if (code === 0) return '晴朗'; if (code <= 3) return '多云'; if (code <= 48) return '雾'; if (code <= 57) return '毛毛雨'; if (code <= 67) return '降雨'; if (code <= 77) return '降雪'; if (code <= 82) return '阵雨'; if (code <= 86) return '阵雪'; return '雷雨'; }
function buildWeatherAdvice(weather: WeatherData, request: TripRequest) { const advice: string[] = []; const today = weather.daily[0]; if (weather.apparentTemperature >= 33 || (today?.max ?? 0) >= 34) advice.push('防暑优先：准备饮水、电解质和遮阳帽；把长时间户外点位避开 12:00–15:00。'); if ((today?.uv ?? 0) >= 6) advice.push(`紫外线指数最高 ${today.uv.toFixed(1)}，建议 SPF30+ 防晒，并每 2–3 小时补涂。`); if ((today?.rainProbability ?? 0) >= 40 || weather.precipitation > 0) advice.push(`降雨概率最高 ${today?.rainProbability ?? 0}%，带折叠伞和防滑鞋；优先保留室内或有遮蔽点位。`); if (weather.windGusts >= 35) advice.push(`阵风约 ${Math.round(weather.windGusts)} km/h，江边和观景台减少使用自拍杆，留意临时封闭。`); if (request.travelerType === '老人' || request.specialNeeds.includes('行动不便')) advice.push('同行包含老人或行动不便需求：每 60–90 分钟安排休息，雨后减少台阶和湿滑栈道路段。'); if (request.specialNeeds.includes('带儿童')) advice.push('带儿童出行：额外准备替换衣物、驱蚊用品和少量补充能量的零食。'); if (!advice.length) advice.push('天气风险较低，按原路线执行即可；仍建议随身带水，并在出发前再次刷新天气。'); return advice.slice(0, 4); }

function Transport({ onSimulate }: { onSimulate?: () => void }) { return <div className="space-y-4"><h4 className="font-display text-2xl font-black">交通查询</h4><div className="rounded-3xl border border-tower/20 bg-tower/10 p-4 text-sm font-bold leading-6"><AlertTriangle className="mb-2 h-5 w-5 text-tower" />本页不提供实时班次。以下仅为“示例数据”，请在出发前通过官方渠道核验。</div><a href="https://www.12306.cn/" target="_blank" rel="noreferrer" className="flex items-center justify-between rounded-2xl bg-white p-4 font-black shadow-sm"><span className="flex items-center gap-2"><TrainFront className="h-5 w-5 text-river" />铁路12306 官方查询</span><ExternalLink className="h-4 w-4" /></a><a href="https://www.amap.com/" target="_blank" rel="noreferrer" className="flex items-center justify-between rounded-2xl bg-white p-4 font-black shadow-sm"><span className="flex items-center gap-2"><Bus className="h-5 w-5 text-river" />高德地图路线查询</span><ExternalLink className="h-4 w-4" /></a><button type="button" onClick={onSimulate} className="w-full rounded-2xl bg-ink px-4 py-3 font-black text-white">演示路线顺序</button></div>; }

function Food({ plan }: { plan: NonNullable<ReturnType<typeof useTrip>['plan']> }) { return <div className="space-y-4"><h4 className="font-display text-2xl font-black">餐饮建议</h4>{plan.foodRecommendations.length ? plan.foodRecommendations.map((food) => <article key={food.id} className="rounded-3xl bg-white p-4 shadow-sm"><h5 className="font-black">{food.name}</h5><p className="mt-2 text-sm font-bold text-ink/60">{food.area} · {food.priceRange}</p><div className="mt-2 flex flex-wrap gap-1">{food.tags.map((tag) => <span key={tag} className="rounded-full bg-jade/10 px-2 py-1 text-xs font-black text-jade">{tag}</span>)}</div><p className="mt-3 text-xs font-bold text-tower">营业状态：{food.businessStatus}</p><a href={food.source.url} target="_blank" rel="noreferrer" className="mt-2 inline-flex items-center gap-1 text-xs font-black text-river">来源：{food.source.name} · 核验 {food.source.checkedAt}<ExternalLink className="h-3 w-3" /></a></article>) : <p className="rounded-2xl bg-white p-4 text-sm font-bold text-ink/55">当前限制条件下没有合适条目，请放宽筛选或自行核验。</p>}</div>; }

function Budget({ items, target, onChange }: { items: BudgetItem[]; target: number; onChange: (items: BudgetItem[]) => void }) {
  const total = budgetTotal(items); return <div className="space-y-4"><div className="flex items-end justify-between"><div><h4 className="font-display text-2xl font-black">预算明细</h4><p className="text-xs font-bold text-ink/50">统一状态自动保存</p></div><strong className={total > target ? 'text-red-600' : 'text-jade'}>¥{total} / ¥{target}</strong></div>{items.map((item) => <div key={item.id} className="grid grid-cols-[1fr_88px_36px] gap-2 rounded-2xl bg-white p-3 shadow-sm"><label className="text-xs font-black text-ink/55">项目<input value={item.item} onChange={(event) => onChange(items.map((value) => value.id === item.id ? { ...value, item: event.target.value } : value))} className="focus-ring mt-1 w-full rounded-lg border border-ink/10 px-2 py-2 text-sm text-ink" /></label><label className="text-xs font-black text-ink/55">金额<input type="number" min={0} value={item.amount} onChange={(event) => onChange(items.map((value) => value.id === item.id ? { ...value, amount: Number(event.target.value) } : value))} className="focus-ring mt-1 w-full rounded-lg border border-ink/10 px-2 py-2 text-sm text-ink" /></label><button type="button" aria-label={`删除${item.item}`} onClick={() => onChange(items.filter((value) => value.id !== item.id))} className="mt-5 grid h-9 place-items-center rounded-lg bg-red-50 text-red-600"><Minus className="h-4 w-4" /></button></div>)}<button type="button" onClick={() => onChange([...items, { id: `budget-${crypto.randomUUID()}`, item: '新条目', amount: 0, note: '' }])} className="inline-flex w-full items-center justify-center gap-2 rounded-2xl border border-dashed border-river/40 px-4 py-3 font-black text-river"><Plus className="h-4 w-4" />新增预算条目</button></div>;
}

function CommandButton({ icon: Icon, label, onClick, disabled, spin }: { icon: typeof RefreshCw; label: string; onClick?: () => void; disabled?: boolean; spin?: boolean }) { return <button type="button" aria-label={label} disabled={disabled} onClick={onClick} className="pointer-events-auto inline-flex items-center gap-2 rounded-full bg-white/90 px-4 py-2 text-xs font-black text-ink shadow-soft backdrop-blur disabled:opacity-60"><Icon className={`h-4 w-4 ${spin ? 'animate-spin' : ''}`} />{label}</button>; }
function Metric({ label, value }: { label: string; value: string }) { return <div className="rounded-2xl bg-ink/88 p-3 text-white shadow-soft backdrop-blur"><div className="text-[10px] font-black uppercase tracking-wider text-white/55">{label}</div><div className="mt-1 font-black">{value}</div></div>; }
function EditableMetric({ label, value, min, max, step = 1, prefix = '', suffix = '', onCommit }: { label: string; value: number; min: number; max: number; step?: number; prefix?: string; suffix?: string; onCommit: (value: number) => void }) { const [draft, setDraft] = useState(String(value)); useEffect(() => setDraft(String(value)), [value]); const commit = () => { const parsed = Number(draft); const next = Number.isFinite(parsed) ? Math.min(max, Math.max(min, parsed)) : value; setDraft(String(next)); onCommit(next); }; return <label className="rounded-2xl bg-white p-4 shadow-sm transition focus-within:ring-4 focus-within:ring-jade/15"><span className="block text-xs font-black text-ink/50">{label}</span><span className="mt-2 flex items-baseline gap-1 font-display text-xl font-black text-ink">{prefix && <span>{prefix}</span>}<input aria-label={`总览${label}`} type="number" min={min} max={max} step={step} value={draft} onChange={(event) => setDraft(event.target.value)} onBlur={commit} onKeyDown={(event) => { if (event.key === 'Enter') event.currentTarget.blur(); }} className="focus-ring min-w-0 w-full bg-transparent font-display text-xl font-black text-ink" />{suffix && <span className="shrink-0 text-sm">{suffix}</span>}</span></label>; }

